# Generated by Django 2.0.6 on 2018-06-11 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180611_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo_tag',
            name='tag',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
