# Generated by Django 2.0.6 on 2018-08-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180611_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='photo_thumb'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
