# Generated by Django 2.1 on 2018-08-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180802_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call_ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=30)),
                ('call_num', models.IntegerField(default=0, verbose_name='访问次数')),
            ],
        ),
    ]
