# Generated by Django 2.1 on 2018-08-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_call_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call_ip',
            name='ip_address',
            field=models.CharField(max_length=30, verbose_name='IP地址'),
        ),
    ]
